YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AbstractAdapter",
        "AbstractDispatcher",
        "Application",
        "CommandBehavior",
        "CommandChain",
        "CommandContext",
        "Controller",
        "ControllerAbstract",
        "DefaultAuthenticator",
        "Dispatcher",
        "Inflector",
        "Mixin",
        "Model",
        "ModelAbstract",
        "MongoAdapter",
        "MysqlAdapter",
        "ObjectIdentifier",
        "ObjectLoader",
        "ObjectManager",
        "Plugin",
        "RaddishError",
        "Role",
        "Router",
        "Row",
        "RowAbstract",
        "Rowset",
        "RowsetAbstract",
        "Socket",
        "SqliteAdapter",
        "States",
        "Table",
        "ViewAbstract",
        "ViewJson"
    ],
    "modules": [],
    "allModules": []
} };
});